name: Automate pages&pdf

on:
  push:
    branches:
    - master

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: "-o index.html -c index.css resume.md -s --title=\"Cenk Pürtaş\""
      - name: Convert to pdf
        run: |
          sudo apt update
          sudo apt -y install wget
          wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
          sudo apt install -f ./wkhtmltox_0.12.5-1.bionic_amd64.deb
          
          wkhtmltopdf --enable-local-file-access --viewport-size 1280x1024 -L 0mm -R 0mm -T 0mm -B 0mm index.html resume.pdf
             
      - name: Upload
        run: |
          # configure git
          git config --global user.name "CePur"
          git config --global user.email "36715887+CePur@users.noreply.github.com"

          # setup ssh
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          
          # Commit changes to pages branch
          git clone --depth=1 --branch gh-pages git@github.com:cepur/resume.git "$GITHUB_WORKSPACE/deploy"          
          cp -f index.html "$GITHUB_WORKSPACE/deploy/index.html"
          cp -f resume.pdf "$GITHUB_WORKSPACE/deploy/resume.pdf"
          cd "$GITHUB_WORKSPACE/deploy"
          git add index.html resume.pdf index.css
          git commit -m "[github actions] deploy"
          git push
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
